### ISSUE TITLE
Testing authorization manually

### ISSUE THREAD

**Issue by chriswiggins** [devinivy/loveboat-nested-scopes#1]
Love what this module looks like it can do (saw it on Twitter) and it definitely does what I need on the Hapi server side.

I'd like to be able to use the user scopes etc inside the SocketIO instance we have attached to our HapiJS server. Is there a way (or somewhere I can start) to make this functionally possible? Maybe an external hook somewhere? Ideally it will just be something like:
```javascript
userScope = ['admin'];

Loveboat.isAllowed(userScope, ['[api-user]'], (err, allowed) => {
  //allowed either true or false
});
```

Appreciate any help and looking forward to potentially extending this module to make this possible :-)

**Comment by devinivy** [comment]
Hi @chriswiggins – glad this looks useful to you!

This module doesn't contain any logic to perform scope matching.  All of that still lives internally to hapi.  However, there is a way to do what you're asking.  You'll want to register a route with `isInternal: true` (using loveboat or just `server.route()`) and whatever access restrictions (i.e. scope) you'd like to test.  This will create a route that is not accessible to the outside world– only to `server.inject()`.  Then, you may make an internal request to that route using,
```js
server.inject({
  method: whatever,
  url: whatever,
  allowInternals: true, // <-- permit the internal request
  credentials: { scope: scopesToTest } // <-- test these scopes
}, (res) => {

   // check res.statusCode and/or res.result.message
});
```

Let me know if that helps.  There's a good example of this in the module [hapijs/nes](https://github.com/hapijs/nes).  If you'd like me to expose the logic used to build the scope tree and to expand a scope, I'm open to that.

**Comment by chriswiggins** [comment]
I've actually just stumbled across the `hapi-io` package which allows you to make Hapi routes that are answered by SocketIO! I've already tried `loveboat-nested-scopes` with this and initial testing shows that it works really, really well.

Thanks so much for your help and module!

**Comment by devinivy** [comment]
Sure thing!  You might be the first person other than myself to get this working, so I'm glad you didn't have any trouble :)
